# Generated by Django 3.1.2 on 2021-01-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('INDIA', 'India'), ('GERMANY', 'Germany'), ('FRANCE', 'France'), ('ARGENTINA', 'Argentina'), ('PARAGUAY', 'Paraguay')], max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('graduate', models.CharField(choices=[('Garduate', 'True'), ('Non-Graduate', 'False')], default='Non-Graduate', max_length=12)),
            ],
        ),
    ]
