# Generated by Django 3.1.2 on 2021-01-31 09:31

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
